/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vt_8_2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Er_xi
 */
public class vt_8_2 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form vt_8_2
     */
    public vt_8_2() {
        initComponents();
        inicio();
    }
    
    public void inicio(){
        blocNotas.setFont(blocNotas.getFont().deriveFont(18f));
        mnItmAbrir.addActionListener(this);
        mnItmSalir.addActionListener(this);
        mnItmCortar.addActionListener(this);
        mnItmCopiar.addActionListener(this);
        mnItmPegar.addActionListener(this);
        mnItmSelAll.addActionListener(this);
        mnItmContar.addActionListener(this);
        mnItmNegro.addActionListener(this);
        mnItmBlanco.addActionListener(this);
        mnItmRojo.addActionListener(this);
        rbPequeña.addActionListener(this);
        rbMediana.addActionListener(this);
        rbGrande.addActionListener(this);
    }
        
    private void examinar() throws IOException {
        JFileChooser examinarArchivos = new JFileChooser();
        int i=examinarArchivos.showOpenDialog(this);
            if(i==JFileChooser.APPROVE_OPTION){
                File fichero = examinarArchivos.getSelectedFile();
                String ficheroPath = fichero.getPath();
            try {
                BufferedReader br = new BufferedReader(new FileReader(ficheroPath));
                String s1="";
                String s2="";
                    while((s1=br.readLine())!=null){
                        s2=s1+"\n";
                    }
                    blocNotas.setText(s2);
                    br.close();
            } catch (Exception ex) {
               ex.printStackTrace();
            }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTamanio = new javax.swing.ButtonGroup();
        pnlBody = new javax.swing.JScrollPane();
        blocNotas = new javax.swing.JTextArea();
        pnlContar = new javax.swing.JPanel();
        lblPalabras = new javax.swing.JLabel();
        lblCaracteres = new javax.swing.JLabel();
        lblPalabraValor = new javax.swing.JLabel();
        lblCaracterValor = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        mnItmAbrir = new javax.swing.JMenuItem();
        mnItmSalir = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        mnItmCopiar = new javax.swing.JMenuItem();
        mnItmCortar = new javax.swing.JMenuItem();
        mnItmPegar = new javax.swing.JMenuItem();
        mnItmSelAll = new javax.swing.JMenuItem();
        mnItmContar = new javax.swing.JMenuItem();
        menuApariencia = new javax.swing.JMenu();
        menuColor = new javax.swing.JMenu();
        mnItmNegro = new javax.swing.JMenuItem();
        mnItmBlanco = new javax.swing.JMenuItem();
        mnItmRojo = new javax.swing.JMenuItem();
        menuTamanio = new javax.swing.JMenu();
        rbPequeña = new javax.swing.JRadioButtonMenuItem();
        rbMediana = new javax.swing.JRadioButtonMenuItem();
        rbGrande = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlBody.setAutoscrolls(true);
        pnlBody.setFocusCycleRoot(true);

        blocNotas.setColumns(20);
        blocNotas.setLineWrap(true);
        blocNotas.setRows(5);
        pnlBody.setViewportView(blocNotas);

        lblPalabras.setText("Palabras:");

        lblCaracteres.setText("Caracteres:");

        javax.swing.GroupLayout pnlContarLayout = new javax.swing.GroupLayout(pnlContar);
        pnlContar.setLayout(pnlContarLayout);
        pnlContarLayout.setHorizontalGroup(
            pnlContarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPalabraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(lblCaracteres)
                .addGap(33, 33, 33)
                .addComponent(lblCaracterValor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        pnlContarLayout.setVerticalGroup(
            pnlContarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCaracterValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPalabraValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPalabras)
                        .addComponent(lblCaracteres)))
                .addContainerGap())
        );

        menuArchivo.setText("Archivo");

        mnItmAbrir.setText("Abrir");
        menuArchivo.add(mnItmAbrir);

        mnItmSalir.setText("Salir");
        menuArchivo.add(mnItmSalir);

        menuBar.add(menuArchivo);

        menuEdicion.setText("Edición");

        mnItmCopiar.setText("Copiar");
        menuEdicion.add(mnItmCopiar);

        mnItmCortar.setText("Cortar");
        menuEdicion.add(mnItmCortar);

        mnItmPegar.setText("Pegar");
        menuEdicion.add(mnItmPegar);

        mnItmSelAll.setText("Seleccionar Todo");
        menuEdicion.add(mnItmSelAll);

        mnItmContar.setText("Contar Palabras");
        menuEdicion.add(mnItmContar);

        menuBar.add(menuEdicion);

        menuApariencia.setText("Apariencia");

        menuColor.setText("Cambiar Color");

        mnItmNegro.setText("Negro");
        menuColor.add(mnItmNegro);

        mnItmBlanco.setText("Blanco");
        menuColor.add(mnItmBlanco);

        mnItmRojo.setText("Rojo");
        menuColor.add(mnItmRojo);

        menuApariencia.add(menuColor);

        menuTamanio.setText("Cambiar Tamaño");

        bgTamanio.add(rbPequeña);
        rbPequeña.setSelected(true);
        rbPequeña.setText("800x600");
        menuTamanio.add(rbPequeña);

        bgTamanio.add(rbMediana);
        rbMediana.setText("1024x768");
        menuTamanio.add(rbMediana);

        bgTamanio.add(rbGrande);
        rbGrande.setText("1920x1024");
        menuTamanio.add(rbGrande);

        menuApariencia.add(menuTamanio);

        menuBar.add(menuApariencia);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody)
            .addComponent(pnlContar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vt_8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vt_8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vt_8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vt_8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vt_8_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTamanio;
    private javax.swing.JTextArea blocNotas;
    private javax.swing.JLabel lblCaracterValor;
    private javax.swing.JLabel lblCaracteres;
    private javax.swing.JLabel lblPalabraValor;
    private javax.swing.JLabel lblPalabras;
    private javax.swing.JMenu menuApariencia;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuColor;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenu menuTamanio;
    private javax.swing.JMenuItem mnItmAbrir;
    private javax.swing.JMenuItem mnItmBlanco;
    private javax.swing.JMenuItem mnItmContar;
    private javax.swing.JMenuItem mnItmCopiar;
    private javax.swing.JMenuItem mnItmCortar;
    private javax.swing.JMenuItem mnItmNegro;
    private javax.swing.JMenuItem mnItmPegar;
    private javax.swing.JMenuItem mnItmRojo;
    private javax.swing.JMenuItem mnItmSalir;
    private javax.swing.JMenuItem mnItmSelAll;
    private javax.swing.JScrollPane pnlBody;
    private javax.swing.JPanel pnlContar;
    private javax.swing.JRadioButtonMenuItem rbGrande;
    private javax.swing.JRadioButtonMenuItem rbMediana;
    private javax.swing.JRadioButtonMenuItem rbPequeña;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==mnItmAbrir){
            try {
                examinar();
            } catch (IOException ex) {
                System.out.println("todo mal");
            }
        }else if(e.getSource()==mnItmSalir){
            dispose();
        }else if(e.getSource()==mnItmCortar){
            blocNotas.cut();
        }else if(e.getSource()==mnItmCopiar){
            blocNotas.paste();
        }else if(e.getSource()==mnItmPegar){
            blocNotas.copy();
        }else if(e.getSource()==mnItmSelAll){
            blocNotas.selectAll();
        }else if(e.getSource()==mnItmContar){
            String texto = blocNotas.getText();
            String words[]=texto.split("\\s");
            lblPalabraValor.setText("Palabras: "+words.length);
            lblCaracterValor.setText("Caracteres: "+texto.length());
        }else if(e.getSource()==mnItmNegro){
            blocNotas.setBackground(Color.black);
        }else if(e.getSource()==mnItmBlanco){
            blocNotas.setBackground(Color.white);
        }else if(e.getSource()==mnItmRojo){
            blocNotas.setBackground(Color.red);
        }else if(e.getSource()==rbPequeña){
            setSize(800, 600);
        }else if(e.getSource()==rbMediana){
            setSize(1024, 768);
        }else if(e.getSource()==rbGrande){
            setSize(1920, 1024);
        }
    }
}
