/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vt_6;

import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Er_xi
 */
public class eje6 extends javax.swing.JFrame implements ChangeListener{
    
    public eje6() {
        initComponents();
        inicio();
    }
    
    public void inicio(){
        rbMin.addChangeListener(this);
        rbMed.addChangeListener(this);
        rbNormal.addChangeListener(this);
        rbGran.addChangeListener(this);
    }
    
    public void cambiarTamanioVentana(String textoBtn){
        String[] textoBoton = textoBtn.split("x");
        String anchostr = textoBoton[0];
        String altostr = textoBoton[1];
        int ancho = Integer.parseInt(anchostr);
        int alto = Integer.parseInt(altostr);
        setSize(ancho,alto);
    }
    
    @Override
    public void stateChanged(ChangeEvent e) {
        AbstractButton aBoton =(AbstractButton)e.getSource();
        ButtonModel aModelo = aBoton.getModel();
            if(aModelo.isSelected()){
                cambiarTamanioVentana(aBoton.getText());
            }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGPTamaños = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbMin = new javax.swing.JRadioButton();
        rbMed = new javax.swing.JRadioButton();
        rbNormal = new javax.swing.JRadioButton();
        rbGran = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elige un tamaño par tu ventana");

        btnGPTamaños.add(rbMin);
        rbMin.setText("600x480");

        btnGPTamaños.add(rbMed);
        rbMed.setText("800x600");

        btnGPTamaños.add(rbNormal);
        rbNormal.setText("1024x768");

        btnGPTamaños.add(rbGran);
        rbGran.setText("1920x1080");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbGran)
                    .addComponent(rbNormal)
                    .addComponent(rbMed)
                    .addComponent(rbMin))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbGran)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGPTamaños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbGran;
    private javax.swing.JRadioButton rbMed;
    private javax.swing.JRadioButton rbMin;
    private javax.swing.JRadioButton rbNormal;
    // End of variables declaration//GEN-END:variables

    
}
